name: Extract ZIP

on:
  push:
    branches:
      - main

jobs:
  extract-zip:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Extract pemrogram.zip
        uses: hoatruongdev09/extract-zip-github-action@v1.2
        with:
          input-path: 'pemrogram.zip'
          output-path: './Web-program/pemrogram-web'  # Ekstrak langsung ke root

      - name: Extract app.zip
        uses: hoatruongdev09/extract-zip-github-action@v1.2
        with:
          input-path: 'app.zip'
          output-path: './Web-program/pemrogram-web'  # Ekstrak langsung ke root
