name: Extract ZIP

on:
  push:
    branches:
      - main

jobs:
  extract-zip:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: action/checkout@v2

      - name: Extract pemrogram-web.zip
        uses: hoatruongdev09/extract-zip-github-action@v1.2
        with:
          input-path: 'pemrogram-web.zip'
          output-path: './'

      - name: Extract app.zip
        uses: hoatruongdev09/extract-zip-github-action@v1.2
        with:
          input-path: 'app.zip'
          output-path: './'
